application: google.com:otp-generator
version: v20150602

runtime: python27
api_version: 1
threadsafe: true

skip_files:
- node_modules

handlers:

- url: /(index\.html)?
  static_files: dist/index.html
  expiration: "365d"
  upload: dist/index.html
  secure: always

- url: /elements/(.*)
  static_files: dist/elements/\1
  expiration: "365d"
  upload: dist/elements/(.*)
  secure: always

- url: /precache.json
  static_files: dist/precache.json
  expiration: "1s"
  upload: dist/precache.json
  secure: always

- url: /sw-import.js
  static_files: dist/sw-import.js
  expiration: "1s"
  upload: dist/sw-import.js
  secure: always

- url: /favicon.ico
  static_files: dist/favicon.ico
  expiration: "365d"
  upload: dist/favicon.ico
  secure: always

- url: /manifest.json
  static_files: dist/manifest.json
  expiration: "1s"
  upload: dist/manifest.json
  secure: always

- url: /scripts/(.*)
  static_files: dist/scripts/\1
  expiration: "1d"
  upload: dist/scripts/(.*)
  secure: always

- url: /sw-toolbox/(.*)
  static_files: dist/sw-toolbox/\1
  expiration: "1d"
  upload: dist/sw-toolbox/(.*)
  secure: always

- url: /third_party/(.*)
  static_files: dist/third_party/\1
  expiration: "1d"
  upload: dist/third_party/(.*)
  secure: always

- url: /styles/(.*)
  static_files: dist/styles/\1
  expiration: "1d"
  upload: dist/styles/(.*)
  secure: always
  application_readable: true

- url: /elements/(.*)
  static_files: dist/elements/\1
  expiration: "1s"
  upload: dist/elements/(.*)
  secure: always

# pagespeed:
#   disabled_rewriters:
#   - add_instrumentation
#   - CombineJs
#   - ConvertMetaTags
#   - FallbackRewriteCssUrls
#   - FlattenCssImports
#   - FlushSubresources
#   - ImageConvertGifToPng
#   - ImageConvertToJpeg
#   - ImageConvertToWebpLossless
#   - ImageResize
#   - InlineImages
#   - InlineImportToLink
#   - InlinePreviewImages
#   - InsertDnsPrefetch
#   - JsOptimize
#   - LazyloadImages
#   - MinifyCss
#   - MoveCssToHead
#   - ProxyCss
#   - ProxyImages
#   - ProxyJs
#   enabled_rewriters:
#   - CombineCss
#   - InlineCss
#   - WebpOptimization
#   - PrioritizeCriticalCss
#   - ImageJpegSubsampling
#   - ImageProgressiveJpeg
#   - ImageRecompressJpeg
#   - ImageRecompressPng
#   - ImageStripColorProfile
#   - ImageStripMetadata
